apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: {{ .Values.namespace | default "default" }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "tls.crt is required" .Values.tlsSecret.crt | b64enc | quote }}
  tls.key: {{ required "tls.key is required" .Values.tlsSecret.key | b64enc | quote }}
  tls.ca: {{ required "tls.ca is required" .Values.tlsSecret.ca | b64enc | quote }}